config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'pages#home'
  get 'about', to: 'pages#about'


  # This one line gave us:
  # a new article path
  # post, to create articles
  # an edit article path
  # a patch, to update articles
  # a delete article path
  # show article path
  # index article path
  resources :articles

  get 'signup', to: 'users#new'

  # The except argument tells Rails that we want all the routes except the users#new route,
  # which we already have as "signup".
  resources :users, except: [:new]

  # This is another possible fix if we don't want to use the resources method. See lecture 119.
  # post 'users', to: 'users#create'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/article.rb
# Enforce validations in the model layer to mantain data integrity.

# NOTE: If you are making CRUD operations from the Rails console, you must
# run "reload!" in the console after making changes to this file.

class Article < ApplicationRecord
    # Note the singular: user
    belongs_to :user

    # Ensures that before an entry can hit the articles database, it must have a title.
    # I.e., the title attribute cannot be nil.
        
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :user_id, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # The following line tells Rails to call the set_article method (private
    # method defined below) right before the edit, update, show, and destroy actions.
    # Note that if you have multiple calls to before_action in a controller, the actions
    # are run from top to bottom. I.e., always make sure that your before_actions calls
    # are in the order that you want them to execute.
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    # For all the actions except the index and show actions, we need the user to be logged in.
    # We also have to make sure that, even for logged-in users, they can't edit 
    # or destory articles they didn't create.
    # Note that including this in the controller safeguards against people reaching pages they shouldn't
    # have access to through the URL.
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index

        # @articles = Article.all
        
        # See https://github.com/mislav/will_paginate for info about this syntax and the
        # will_paginate gem.
        @articles = Article.paginate(page: params[:page], per_page: 5)

        # print_to_console(@articles)
    end

    # Displays new article form (new.html.erb)
    def new
        # Create a new instance of Article, our model class for the 
        # articles table. This instance variable is then available in
        # our view for the new action (i.e., in the new.html.erb file).
        # For more details about this Rails magic:
        # https://stackoverflow.com/questions/18773172/rails-how-do-controllers-pass-instance-variables-to-views-can-it-be-stopped/18774043
        # https://medium.com/@eric.programmer/removing-the-hack-in-rails-controllers-52396463c40d
        @article = Article.new

        # print_to_console(params)

    end

    # Displays edit article form (edit.html.erb)
    def edit
        
    end



    # The create method automatically receives params from the new article form submission.
    # (This form is contained in new.html.erb.)
    # Thus, it handles the new article form submission.
    def create

        # Uses the byebug gem (automatically included in Rails) to create a breakpoint
        # so that we can see the values of variables at this point + run through
        # execution line by line from here on out.
        # See: https://github.com/deivid-rodriguez/byebug
        # debugger

        # The line below lets us see params[:article].
        # I added parentheses to make it easier to read, but it can also
        # be written as "render plain: params[:article].inspect".
        # Note: params is actually an object, not a Ruby Hash!
        # See: https://eileencodes.com/posts/actioncontroller-parameters-now-returns-an-object-instead-of-a-hash/
        # render(plain: (params[:article].inspect))
        
        # print_to_console(params)

        @article = Article.new(article_params)

        # Set the creator to be the current user
        @article.user = current_user

        if @article.save
            # See: https://api.rubyonrails.org/classes/ActionDispatch/Flash.html
            # Also: http://www.xyzpub.com/en/ruby-on-rails/3.2/flash.html
            # Note that :success gives you green
            flash[:success] = 'Article was successfully created.'

            # This redirects to the articles#show action for this article.
            # Remember, to get the path for the show action, run "rails routes"
            # and then look at the "Prefix" column for the articles#show action. Append
            # "_path" to what you see there to get the path. We must pass in @article
            # because the URL requires the article id. (I guess Rails pulls out
            # the article id behind the scenes.)
            redirect_to article_path(@article)
        else

            # print "\n--------------------------------------------------\n"
            # puts @article
            # print "--------------------------------------------------\n\n"

            # print_to_console(@article.description)

            # Render the new.html.erb template once again if we fail to save
            # We could also use a symbol: "render :new"
            render 'new'
        end

    end

    # Handles the edit article form submission (edit.html.erb)
    def update
        
        # print_to_console(@article)

        # print_to_console(params)

        if @article.update(article_params)

            flash[:success] = 'Article was successfully updated.'
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
        
    def show

        # print_to_console(params)

        
    end


    def destroy
        

        @article.destroy

        # :danger makes it red
        flash[:danger] = "Article was successfully deleted."

        redirect_to articles_path
    end

    
    private

        def set_article
            @article = Article.find(params[:id])
        end

        # Whitelist whatever has been submitted
        def article_params

            params.require(:article).permit(:title, :description)


        end

        # Used to ensure that users can't edit/delete articles they didn't create
        def require_same_user

            # We know current_user isn't nil because we ran require_user before this method.
            # See the order of the before_action calls at the top of this controller.
            # Likewise, we know that @article is defined because set_article is called before
            # this method thanks to the order of our before_action calls.
            if current_user != @article.user && !current_user.admin?
                flash[:danger] = "You can only edit or delete your own articles."
                redirect_to root_path

            end
        end

end


# Helper for printing to console
def print_to_console(input)
    print "\n--------------------------------------------------\n"
    print "#{input}\n"
    print "--------------------------------------------------\n\n"
end

# Method to test something
def test
    session[:user_id] = nil
    current_user
end

app/views/articles/_article.html.erb
<%# I feel like this code should be put in the vews/shared directory since
it is used in articles/index.html.erb and users/show.html.erb %>


<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                
                <div class="article-body">
                    <%# Truncate the article's description to 100 characters %>
                    <%= truncate(article.description, length: 100) %>

                    <div class="article-meta-details">
                        <%# The if statement is a temporary fix because at the time of writing,
                        some articles in the database aren't associated to users. %>
                        <small>Created by: <%= article.user.username if article.user %>,
                                <%= time_ago_in_words(article.created_at) %> ago,
                                last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>

                <%# Only display the delete and edit buttons if the user is logged in and actually
                wrote that article. %>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class="article-actions">
                        <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

                        <%# The "method: :delete" part tells Rails that we want the articles#destroy action,
                            not the articles#show action. %>
                        <%= link_to "Delete this article", article_path(article), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete the article?" }, 
                                                class: "btn btn-xs btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%# This is a partial, as indicated by the _ in the file name.
Partials allow us to reuse code. %>

<%# Render the partial contained in views/shared/_errors.html.erb %>
<%# It displays errors messages. %>
<%# Note that we pass in @article as obj. We could simply reference @article in the _errors partial since
instance variables automatically get passed along to rendered partials, but since _errors is in the
/shared directory, we want to be able to run its code from multiple /view subdirectories. Thus,
we want _errors to be able to work with other objects that might have errors attached (e.g., @user).
Therefore, we pass in @article as obj. %>
<%= render 'shared/errors', obj: @article %>

<%#
Here we use a form_for helper.
For more info about form helpers in Rails, see:
https://guides.rubyonrails.org/form_helpers.html
%>
<%# Note that the @article variable used below
must be initialized in ArticlesController. %>

<%# The styling below is based on the "horizontal form" code from the following page:
https://getbootstrap.com/docs/3.3/css/#forms %>
<div class="row">
    <div class='col-xs-12'>
        <%# If you look at the "horizontal form" code, it is wrapped in form tags with the class
        "form-horizontal". However we can't do this here because the embedded Ruby line below with
        the "form_for" function actually returns HTML with a form tag. Thus, if we also wrap the code
        in form tags like Bootstrap prescribes, we would have duplicate form tags, and Rails would give an error.
        The following line therefore is a workaround to add the "form-horizontal" class to our generated
        form tag. Note that we do need the "form-horizontal" class to get the styling we want. %>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        <% end %>
        
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Bad Beagle Encounters</h1>

<div align="center">
    <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Let Out Your Rage!</h1>

<%# Render the partial contained in the _form.html.erb file %>
<%= render 'form' %>

<%# Note that we must always specify the relative path to the file.
E.g., if the file was contained in a "share" folder in the same directory,
we would put: render 'share/form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

    <%# This if statement is a temporary fix because at the time of writing
    some articles don't have associated users. %>
    <% if @article.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %> </li>

                    <%# The line below uses the class "article-title" simply because we want the 
                    username to have the same styling as article titles. Obviously this isn't optimal naming. %>
                    <li class="article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>

                    <%# user.articles.count obviously returns the number of articles written by that user. %>
                    <%# Notice that we only want to display something if the user has written some number of articles. %>
                    <li><small>
                        <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                    </small></li>
                </div>
            </div>
        </ul>
    <% end %>

    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%# The simple_format methods saves formatting. E.g., if when you
    created the article you added blank lines, returns, tabs, etc., simple_format
    ensures that when the article is displayed, those are preserved. %>
    <%= simple_format(@article.description) %>

    <div class="article-actions">

        <%# The user should only be able to access the delete and edit buttons if they are logged
        in and actually wrote the article. %>
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

            <%# The "method: :delete" part tells Rails that we want the articles#destroy action,
                not the articles#show action. %>
            <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                    data: { confirm: "Are you sure you want to delete the article?" }, 
                                    class: "btn btn-xs btn-danger" %>
        <% end %>

        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>