config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'pages#home'
  get 'about', to: 'pages#about'


  # This one line gave us:
  # a new article path
  # post, to create articles
  # an edit article path
  # a patch, to update articles
  # a delete article path
  # show article path
  # index article path
  resources :articles

  get 'signup', to: 'users#new'

  # The except argument tells Rails that we want all the routes except the users#new route,
  # which we already have as "signup".
  resources :users, except: [:new]

  # This is another possible fix if we don't want to use the resources method. See lecture 119.
  # post 'users', to: 'users#create'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            &copy; 2019 Liam O'Carroll, Anti-Beagle Activist
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<%# Flash a message to the user %>
<%# E.g., error message, success message, etc. %>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <%# The name parameter is the message type. E.g., "danger," "success," etc. %>
        <% flash.each do |name, msg| %>
            <%# Note the use of the double quotes inside single quotes in the line below. %>
            <div class='alert alert-<%= "#{name}" %>'>
                <%# Create an X (close popup icon) so that users can dismiss the message. %>
                <%# The &#215 part is responsible for actually causing the X icon to be displayed (as %>
                <%# opposed to some other icon). %>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<%# This is the "default navbar" copied from the following page:
https://getbootstrap.com/docs/3.3/components/#navbar %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


      <%# The two lines below are almost identical. In fact, the upper one was the original
      and the lower one is the upper one turned into embedded Ruby code. We choose to use the lower
      one because we want the logo to always link to the root path, and embedded ruby
      gives us an easy way to do this. %>
      <%# <a class="navbar-brand" id="logo" href="#">Alpha Blog</a> %>
      <%= link_to "Beagles Are Evil", root_path, class: "navbar-brand", id: "logo" %>


      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <%# The following line has been converted into embedded Ruby below. It turns out that the 
        "sr-only" class has to do with screen-reader users." %>
        <%# <li><a href="#">Link <span class="sr-only">(current)</span></a></li> %>

        <li><%= link_to "Articles", articles_path %><li>
        <li><%= link_to "Users", users_path %></li>

        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">


              <%# <li><a href="#">Action</a></li> %>
              <li><%= link_to "New Article", new_article_path %><li>

              <%# <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li> %>
            </ul>
          </li>
        <% end %>


      </ul>
      <%# <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> %>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <%# Because the logout path is handled by a delete action, we have to
          specify as an argument that the action is delete. %>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
                aria-expanded="false">Your Profile <%= "(Admin)" if current_user.admin? %>
                <span class="caret"></span></a>
            <ul class="dropdown-menu">

              <%# Note that the edit_user_path(current_user) call in the line below won't blow
              up because we've already checked that the user is logged in. %>
              <li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Your Profile", user_path(current_user) %></li>
              <%# <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li> %>
            </ul>
          </li>

        <% else %>
          <li><%= link_to 'Log In', login_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<%# This file wraps all of your views. %>
<%# Thus, anything you put in here will be displayed on every page. %>


<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%# <%
      print "\n--------------------------------------------------\n"
      print "INSIDE application.html.erb\n"
      print "flash: #{flash}\n"
      print "flash.class: #{flash.class}\n"
      print "flash[:notice]: #{flash[:notice]}\n"
      print "--------------------------------------------------\n\n"
    %> 

    <%= render 'layouts/navigation' %>
    
    <%# By default Rails looks for the messages partial in the articles folder
    since that is where the views for our actions (related to articles) are.
    Thus, we must specify this path. %>
    <%# Note: He includes this partial because he recommends having as little code
    as possible in the application.html.erb file. %>
    <%= render 'layouts/messages' %>
    
    <%# Create a container so that elements aren't flush against the edge of the screen. %>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

    <%# Causes there to be a display of params if we are working in the development environment %>
    <%= debug(params) if Rails.env.development? %>

    <%= debug(session[:user_id]) if Rails.env.development? %>

    <%= debug(@current_user) if Rails.env.development? %>
  </body>
</html>